on: [push, pull_request, workflow_dispatch]

jobs:
  vars:
    runs-on: ubuntu-latest
    outputs:
      date_stamp: ${{ steps.date_step.outputs.date_stamp }}
      short_sha: ${{ steps.short_sha_step.outputs.short_sha }}
    steps:
      - id: date_step
        run: echo "date_stamp='$(date +%Y%m%d-%H%M%S)'" >> $GITHUB_OUTPUT
      - id: short_sha_step
        run: echo "short_sha='${GITHUB_SHA::7}'" >> $GITHUB_OUTPUT
  build:
    needs: [ vars ]
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      archive_name: "hix-corne-${{ needs.vars.outputs.short_sha }}-${{ needs.vars.outputs.date_stamp }}"


