# yamllint disable rule:line-length
---
name: Build
on:  # yamllint disable-line rule:truthy
  - push
  - pull_request
  - workflow_dispatch

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    strategy:
      fail-fast: true
      matrix:
        include:
          - shield: corne_left
            board: nice_nano
            artifact_prefix: hix_01
            keyboard_name: "Hix Corne L 01"  # ZMK_KEYBOARD_NAME must be less than 16 characters due to device BLE device name length limit.

          - shield: corne_right
            board: nice_nano
            artifact_prefix: hix_01
            keyboard_name: "Hix Corne R 01"

          - shield: corne_left
            board: nice_nano
            artifact_prefix: hix_02
            keyboard_name: "Hix Corne L 02"

          - shield: corne_right
            board: nice_nano
            artifact_prefix: hix_02
            keyboard_name: "Hix Corne R 02"

          - shield: settings_reset
            board: nice_nano
            artifact_prefix: reset
            keyboard_name: "reset"

    steps:
      - name: Checkout (${{ matrix.keyboard_name }})
        uses: actions/checkout@v2

      - name: Fetch Git Metadata (${{ matrix.keyboard_name }})
        id: git
        run: echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"

      - name: Cache west modules (${{ matrix.keyboard_name }})
        uses: actions/cache@v2
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('manifest-dir/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: West Init (${{ matrix.keyboard_name }})
        run: west init -l config

      - name: West Update (${{ matrix.keyboard_name }})
        run: west update

      - name: West Zephyr export (${{ matrix.keyboard_name }})
        run: west zephyr-export

      - name: West Build (${{ matrix.keyboard_name }})
        run: west build --pristine -s zmk/app -b ${{ matrix.board }} -- -DSHIELD=${{ matrix.shield }} -DZMK_CONFIG="${GITHUB_WORKSPACE}/config" -DCONFIG_ZMK_KEYBOARD_NAME="\"${{ matrix.keyboard_name }}\""

      - name: Corne Kconfig file (${{ matrix.keyboard_name }})
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"

      - name: Rename Artifact (${{ matrix.keyboard_name }})
        run: cp build/zephyr/zmk.uf2 ${{ matrix.artifact_prefix }}_${{ matrix.shield }}_${{ matrix.board }}.uf2

      - name: Archive Artifact (${{ matrix.keyboard_name }})
        uses: actions/upload-artifact@v2
        with:
          name: firmware-${{ steps.git.outputs.short_sha }}
          path: ${{ matrix.artifact_prefix }}_${{ matrix.shield }}_${{ matrix.board }}.uf2
